# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Sun Jun 07 21:58:27 2015
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1334, 725)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 961, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 951, 491))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.Title_textEdit = QtGui.QTextEdit(self.tab_3)
        self.Title_textEdit.setGeometry(QtCore.QRect(10, 30, 921, 31))
        self.Title_textEdit.setObjectName(_fromUtf8("Title_textEdit"))
        self.Content_textEdit = QtGui.QTextEdit(self.tab_3)
        self.Content_textEdit.setGeometry(QtCore.QRect(10, 100, 921, 351))
        self.Content_textEdit.setObjectName(_fromUtf8("Content_textEdit"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 931, 221))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.avr_list1_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list1_pushButton.setGeometry(QtCore.QRect(390, 20, 71, 31))
        self.avr_list1_pushButton.setObjectName(_fromUtf8("avr_list1_pushButton"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(470, 70, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.avr_list4_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list4_pushButton.setGeometry(QtCore.QRect(850, 60, 71, 31))
        self.avr_list4_pushButton.setObjectName(_fromUtf8("avr_list4_pushButton"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(470, 150, 101, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.avr_list7_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list7_pushButton.setGeometry(QtCore.QRect(390, 140, 71, 31))
        self.avr_list7_pushButton.setObjectName(_fromUtf8("avr_list7_pushButton"))
        self.avr_list9_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list9_pushButton.setGeometry(QtCore.QRect(390, 180, 71, 31))
        self.avr_list9_pushButton.setObjectName(_fromUtf8("avr_list9_pushButton"))
        self.avr_list7_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list7_textEdit.setGeometry(QtCore.QRect(110, 140, 271, 31))
        self.avr_list7_textEdit.setObjectName(_fromUtf8("avr_list7_textEdit"))
        self.avr_list2_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list2_textEdit.setGeometry(QtCore.QRect(570, 20, 271, 31))
        self.avr_list2_textEdit.setObjectName(_fromUtf8("avr_list2_textEdit"))
        self.avr_list10_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list10_pushButton.setGeometry(QtCore.QRect(850, 180, 71, 31))
        self.avr_list10_pushButton.setObjectName(_fromUtf8("avr_list10_pushButton"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.avr_list10_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list10_textEdit.setGeometry(QtCore.QRect(570, 180, 271, 31))
        self.avr_list10_textEdit.setObjectName(_fromUtf8("avr_list10_textEdit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(470, 30, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.avr_list6_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list6_pushButton.setGeometry(QtCore.QRect(850, 100, 71, 31))
        self.avr_list6_pushButton.setObjectName(_fromUtf8("avr_list6_pushButton"))
        self.avr_list6_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list6_textEdit.setGeometry(QtCore.QRect(570, 100, 271, 31))
        self.avr_list6_textEdit.setObjectName(_fromUtf8("avr_list6_textEdit"))
        self.avr_list8_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list8_textEdit.setGeometry(QtCore.QRect(570, 140, 271, 31))
        self.avr_list8_textEdit.setObjectName(_fromUtf8("avr_list8_textEdit"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(460, 190, 111, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.avr_list5_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list5_textEdit.setGeometry(QtCore.QRect(110, 100, 271, 31))
        self.avr_list5_textEdit.setObjectName(_fromUtf8("avr_list5_textEdit"))
        self.avr_list9_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list9_textEdit.setGeometry(QtCore.QRect(110, 180, 271, 31))
        self.avr_list9_textEdit.setObjectName(_fromUtf8("avr_list9_textEdit"))
        self.avr_list2_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list2_pushButton.setGeometry(QtCore.QRect(850, 20, 71, 31))
        self.avr_list2_pushButton.setObjectName(_fromUtf8("avr_list2_pushButton"))
        self.avr_list8_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list8_pushButton.setGeometry(QtCore.QRect(850, 140, 71, 31))
        self.avr_list8_pushButton.setObjectName(_fromUtf8("avr_list8_pushButton"))
        self.avr_list1_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list1_textEdit.setGeometry(QtCore.QRect(110, 20, 271, 31))
        self.avr_list1_textEdit.setObjectName(_fromUtf8("avr_list1_textEdit"))
        self.avr_list4_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list4_textEdit.setGeometry(QtCore.QRect(570, 60, 271, 31))
        self.avr_list4_textEdit.setObjectName(_fromUtf8("avr_list4_textEdit"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(470, 110, 101, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.avr_list3_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list3_pushButton.setGeometry(QtCore.QRect(390, 60, 71, 31))
        self.avr_list3_pushButton.setObjectName(_fromUtf8("avr_list3_pushButton"))
        self.avr_list5_pushButton = QtGui.QPushButton(self.groupBox)
        self.avr_list5_pushButton.setGeometry(QtCore.QRect(390, 100, 71, 31))
        self.avr_list5_pushButton.setObjectName(_fromUtf8("avr_list5_pushButton"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 101, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.avr_list3_textEdit = QtGui.QTextEdit(self.groupBox)
        self.avr_list3_textEdit.setGeometry(QtCore.QRect(110, 60, 271, 31))
        self.avr_list3_textEdit.setObjectName(_fromUtf8("avr_list3_textEdit"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 471, 221))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(0, 30, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.wz_list1_textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.wz_list1_textEdit.setGeometry(QtCore.QRect(90, 20, 291, 31))
        self.wz_list1_textEdit.setObjectName(_fromUtf8("wz_list1_textEdit"))
        self.wz_list1_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.wz_list1_pushButton.setGeometry(QtCore.QRect(390, 20, 71, 31))
        self.wz_list1_pushButton.setObjectName(_fromUtf8("wz_list1_pushButton"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(0, 70, 101, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.wz_list2_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.wz_list2_pushButton.setGeometry(QtCore.QRect(390, 60, 71, 31))
        self.wz_list2_pushButton.setObjectName(_fromUtf8("wz_list2_pushButton"))
        self.wz_list2_textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.wz_list2_textEdit.setGeometry(QtCore.QRect(90, 60, 291, 31))
        self.wz_list2_textEdit.setObjectName(_fromUtf8("wz_list2_textEdit"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(0, 110, 101, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.wz_list3_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.wz_list3_pushButton.setGeometry(QtCore.QRect(390, 100, 71, 31))
        self.wz_list3_pushButton.setObjectName(_fromUtf8("wz_list3_pushButton"))
        self.wz_list3_textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.wz_list3_textEdit.setGeometry(QtCore.QRect(90, 100, 291, 31))
        self.wz_list3_textEdit.setObjectName(_fromUtf8("wz_list3_textEdit"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(0, 150, 101, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.wz_list4_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.wz_list4_pushButton.setGeometry(QtCore.QRect(390, 140, 71, 31))
        self.wz_list4_pushButton.setObjectName(_fromUtf8("wz_list4_pushButton"))
        self.wz_list4_textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.wz_list4_textEdit.setGeometry(QtCore.QRect(90, 140, 291, 31))
        self.wz_list4_textEdit.setObjectName(_fromUtf8("wz_list4_textEdit"))
        self.wz_list5_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.wz_list5_pushButton.setGeometry(QtCore.QRect(390, 180, 71, 31))
        self.wz_list5_pushButton.setObjectName(_fromUtf8("wz_list5_pushButton"))
        self.wz_list5_textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.wz_list5_textEdit.setGeometry(QtCore.QRect(90, 180, 291, 31))
        self.wz_list5_textEdit.setObjectName(_fromUtf8("wz_list5_textEdit"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(0, 190, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.cs_pushButton = QtGui.QPushButton(self.tab_4)
        self.cs_pushButton.setGeometry(QtCore.QRect(822, 7, 121, 41))
        self.cs_pushButton.setObjectName(_fromUtf8("cs_pushButton"))
        self.cs_Title_textEdit = QtGui.QTextEdit(self.tab_4)
        self.cs_Title_textEdit.setGeometry(QtCore.QRect(10, 10, 801, 31))
        self.cs_Title_textEdit.setObjectName(_fromUtf8("cs_Title_textEdit"))
        self.cs_Content_textEdit = QtGui.QTextEdit(self.tab_4)
        self.cs_Content_textEdit.setGeometry(QtCore.QRect(10, 50, 931, 411))
        self.cs_Content_textEdit.setObjectName(_fromUtf8("cs_Content_textEdit"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(790, 497, 151, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_9 = QtGui.QGroupBox(Dialog)
        self.groupBox_9.setGeometry(QtCore.QRect(970, 10, 351, 561))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.messagebox = QtGui.QTextEdit(self.groupBox_9)
        self.messagebox.setGeometry(QtCore.QRect(10, 20, 331, 531))
        self.messagebox.setObjectName(_fromUtf8("messagebox"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 570, 301, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.username_textEdit = QtGui.QTextEdit(self.groupBox_3)
        self.username_textEdit.setGeometry(QtCore.QRect(60, 30, 231, 31))
        self.username_textEdit.setObjectName(_fromUtf8("username_textEdit"))
        self.password_textEdit = QtGui.QTextEdit(self.groupBox_3)
        self.password_textEdit.setGeometry(QtCore.QRect(60, 70, 231, 31))
        self.password_textEdit.setObjectName(_fromUtf8("password_textEdit"))
        self.Login_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.Login_pushButton.setGeometry(QtCore.QRect(40, 110, 221, 31))
        self.Login_pushButton.setObjectName(_fromUtf8("Login_pushButton"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 570, 651, 151))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 60, 93, 28))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 191, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.blog_pushButton = QtGui.QPushButton(self.groupBox_5)
        self.blog_pushButton.setGeometry(QtCore.QRect(30, 80, 121, 28))
        self.blog_pushButton.setObjectName(_fromUtf8("blog_pushButton"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "搜狐BLOG文章群发(单用户版本)", None))
        self.label.setText(_translate("Dialog", "内容 Content(支持变量)", None))
        self.label_2.setText(_translate("Dialog", "标题 Title(支持变量)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "文章", None))
        self.groupBox.setTitle(_translate("Dialog", "关键字/链接/(一行一个)", None))
        self.label_3.setText(_translate("Dialog", "{avr_list1}：", None))
        self.avr_list1_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_6.setText(_translate("Dialog", "{avr_list4}：", None))
        self.avr_list4_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_10.setText(_translate("Dialog", "{avr_list8}：", None))
        self.avr_list7_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.avr_list9_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.avr_list10_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_5.setText(_translate("Dialog", "{avr_list3}：", None))
        self.label_4.setText(_translate("Dialog", "{avr_list2}：", None))
        self.avr_list6_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_12.setText(_translate("Dialog", "{avr_list10}：", None))
        self.avr_list2_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.avr_list8_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_8.setText(_translate("Dialog", "{avr_list6}：", None))
        self.label_7.setText(_translate("Dialog", "{avr_list5}：", None))
        self.label_9.setText(_translate("Dialog", "{avr_list7}：", None))
        self.avr_list3_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.avr_list5_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_11.setText(_translate("Dialog", "{avr_list9}：", None))
        self.groupBox_2.setTitle(_translate("Dialog", "伪原创文章(以句号分割)", None))
        self.label_13.setText(_translate("Dialog", "{wz_list1}：", None))
        self.wz_list1_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_14.setText(_translate("Dialog", "{wz_list2}：", None))
        self.wz_list2_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_15.setText(_translate("Dialog", "{wz_list3}：", None))
        self.wz_list3_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_16.setText(_translate("Dialog", "{wz_list4}：", None))
        self.wz_list4_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.wz_list5_pushButton.setText(_translate("Dialog", "浏览文件", None))
        self.label_17.setText(_translate("Dialog", "{wz_list5}：", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "变量(关键字/链接)", None))
        self.cs_pushButton.setText(_translate("Dialog", "生成文章", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "浏览文章", None))
        self.pushButton.setText(_translate("Dialog", "保存配置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "文章", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "说明", None))
        self.groupBox_9.setTitle(_translate("Dialog", "messagebox消息提示", None))
        self.groupBox_3.setTitle(_translate("Dialog", "第一步登陆", None))
        self.label_19.setText(_translate("Dialog", "密码：", None))
        self.label_18.setText(_translate("Dialog", "账号：", None))
        self.password_textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1234567890</p></body></html>", None))
        self.Login_pushButton.setText(_translate("Dialog", "登陆搜狐博客", None))
        self.groupBox_4.setTitle(_translate("Dialog", "第二步发布文章/发布微博 等", None))
        self.pushButton_3.setText(_translate("Dialog", "PushButton", None))
        self.groupBox_5.setTitle(_translate("Dialog", "发布文章", None))
        self.blog_pushButton.setText(_translate("Dialog", "发布博客", None))

